package com.seentechs.newtaxidriver.common.util

/**
 * Created by Seen Technologies on 9/8/18.
 */

object Enums {


    val REQ_REG = 100
    val REQ_NUM_VALID = 101
    val REQ_UPDATE_ONLINE = 102
    val REQ_DRIVER_STATUS = 103
    val REQ_DEVICE_STATUS = 104
    val REQ_LOGOUT = 105
    val REQ_DRIVER_PROFILE = 106
    val REQ_CURRENCY = 107
    val REQ_LANGUAGE = 108
    val REQ_ARRIVE_NOW = 109
    val REQ_BEGIN_TRIP = 110
    val REQ_END_TRIP = 111
    val REQ_UPDATE_PROFILE = 112
    val REQ_UPLOAD_PROFILE_IMG = 113

    val REQ_CURRENCYLIST = 122
    val REQ_UPLOAD_PAYOUT = 123
    val REQ_GET_STRIPE = 124
    val REQ_GET_INVOICE = 126
    val REQ_CASH_COLLECTED = 127
    val REQ_VIEW_PAYMENT = 128
    val REQ_ADD_CARD = 129
    val REQ_CANCEL_TRIP = 130
    val REQ_CANCEL = 131
    val REQ_WEEKLY_TRIP_STATEMENT = 132
    val REQ_WEEKLY_STATEMENT = 133
    val REQ_DAILY_STATEMENT = 134
    val REQ_TOLL_REASON = 135
    val REQ_HEAT_MAP = 136
    val REQ_COMMON_DATA = 137
    val REQ_UPDATE_CURRENCY = 138
    val REQ_TRIP_DETAILS = 139
    val REQ_PAST_TRIPS = 140
    val REQ_UPCOMING_TRIPS = 141
    val REQ_RIDER_PROFILE = 142
    val REQ_CURRENCY_CONVERT = 143
    val REQ_PAY_TO_ADMIN = 144
    val REG_GET_PAYMENTMETHOD= 145
    val REG_VEHICLE_DESCRIPTION= 146
    val UPLOAD_DRIVER_DOCUMENT= 147
    val ADD_UPDATE_VEHICLE= 148
    val UPDATE_DEFAULT_VEHICLE= 149
    val DELETE_VEHICLE= 150
    val UPLOAD_VEHICLE_DOCUMENT= 151
    val REG_GET_CHECK_VERSION=152
    const val REQ_OTP_VERIFIACTION=153


    val USER_CHOICE_LANGUAGE = "language"
    val USER_CHOICE_CURRENCY = "currency"
    val USER_CHOICE_COUNTRY = "country"
    val USER_CHOICE_STRIPE_COUNTRY = "stripe_country"
    val USER_CHOICE_STRIPE_CURRENCY = "stripe_currency"
    val USER_CHOICE_STRIPE_GENDER = "stripe_gender"

}
